### ISSUE TITLE
Chinese language fallback.

### ISSUE THREAD

**Issue by c933103** [LobbyDivinus/theotown-translation#547]
Currently, the game have two varoants of Chinese translations in the game: Chinese (unspecified) and Chinese (Taiwan)
All users with Chinese locale setting that are not Taiwan will currently fallback to the unlabelled variant.
However, this is undesirable and unexpected by some users.
The unspecified translation contain a Chinese translation written in Simplified Chinese, while the Taiwan translation contain a Chinese Translation written in Traditional Chinese.
There are some other population who use Traditional Chinese as their main form of written Chinese communication, including Hong Kong and Macau, but in the current configuration in the game they're fallback to the unspecified variant of Chinese which use Simplified Chinese, which is undesirable.
Please change the language fallback in these region to Chinese (Taiwan) instead.

**Comment by LobbyDivinus** [comment]
Thank you, I will have a look into that. Von: c933103Gesendet: Mittwoch, 9. September 2020 06:38An: LobbyDivinus/theotown-translationCc: SubscribedBetreff: [LobbyDivinus/theotown-translation] Chinese language fallback. (#547) Currently, the game have two varoants of Chinese translations in the game: Chinese (unspecified) and Chinese (Taiwan)All users with Chinese locale setting that are not Taiwan will currently fallback to the unlabelled variant.However, this is undesirable and unexpected by some users.The unspecified translation contain a Chinese translation written in Simplified Chinese, while the Taiwan translation contain a Chinese Translation written in Traditional Chinese.There are some other population who use Traditional Chinese as their main form of written Chinese communication, including Hong Kong and Macau, but in the current configuration in the game they're fallback to the unspecified variant of Chinese which use Simplified Chinese, which is undesirable.Please change the language fallback in these region to Chinese (Taiwan) instead.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by JustAnyones** [comment]
Should TM be fixed in version [1.9.39](https://forum.theotown.com/viewtopic.php?p=164297#p164297)
